# Generated by Django 3.0.6 on 2022-01-07 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('bloodgroup', models.CharField(max_length=20)),
                ('neededBlood', models.CharField(max_length=20)),
                ('locations', models.CharField(max_length=50)),
                ('requestDate', models.DateTimeField(max_length=50)),
                ('currentDate', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articale', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-currentDate'],
            },
        ),
    ]
