# Generated by Django 3.2.9 on 2022-01-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
