# Generated by Django 3.0.6 on 2022-01-07 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='default_user_profile.png', upload_to='UserProfile/Profilepic/')),
                ('phone', models.CharField(max_length=20)),
                ('DateOfBirth', models.DateField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('bloodGroup', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('thana', models.CharField(max_length=30)),
                ('union', models.CharField(max_length=30)),
                ('postCode', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=30)),
                ('published', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
