# Generated by Django 3.0.6 on 2022-01-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='UserProfile/Profilepic/default_user_profile.png', upload_to='UserProfile/Profilepic/'),
        ),
    ]
